- id: "check-yaml"
  name: "Check Yaml"
  entry: check-yaml
  types: [yaml]
  language: python
  verbose: true
  description: "This is an example hook to demonstrate how to execute python (.py) files."

